image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      composer install &&
      nohup sudo docker-up &&
      sleep 5 &&
      docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASS &&
      echo "WEB_HOST=8800-"`echo $GITPOD_WORKSPACE_URL | sed -e 's|^[^/]*//||' -e 's|/.*$||'`> .env &&
      docker-compose pull --parallel
    command: docker-compose up -d
ports:
  - port: 8800
  - port: 3206
    onOpen: ignore
  #- port: 8025
  #  onOpen: ignore
