image:
  file: .gitpod.Dockerfile

tasks:
  - init: >
      composer install &&
      sudo docker-up &&
      docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASS &&
      docker-compose up -d
ports:
  - port: 8800
  - port: 3206
    onOpen: ignore
  #- port: 8025
  #  onOpen: ignore
