uri: 'public:/'
compact_snippet: true
include_file: true
rebuild_snippets: true
flush_snippets: false
debug_output: true
_default_container:
  container_id: ''
  path_toggle: all_except_listed
  path_list: "admin*\nbatch*\nnode/add*\nnode/*/*\nuser/*/*"
  role_toggle: all_except_listed
  role_list:
    - null
  status_toggle: ''
  status_list: "403\n404"
  compact_tag: true
