status: true
id: primary
label: Primary
weight: 0
container_id: GTM-MPHNMQ
path_toggle: all_except_listed
path_list: "admin*\nbatch*\nnode/add*\nnode/*/*\nuser/*/*"
role_toggle: all_except_listed
role_list:
  - null
status_toggle: ''
status_list: "403\n404"
compact_tag: true
