max_links: 10000
cron_generate: true
cron_generate_interval: 3
remove_duplicates: false
skip_untranslated: true
batch_process_limit: 1500
base_url: 'https://www.mass.gov'
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
_core:
  default_config_hash: vFARRSP9-YgEArfDNYmRSg0cNFOgZPxqziffIalgLbU
