token: b3a1ab0c28be4e3d8e9d06f65c333205
_core:
  default_config_hash: t5W6QbLZA8s7VAoHDDldhRB2Emm1blOGOOKHMV855Gk
domain_plugin_id: siteimprovedomain_simple
prepublish_enabled: true
api_username: arthur@lastcallmedia.com
api_key: 6e8faa7fedff5dc35069eb894f4e52a0
enabled_content_types:
  action: action
  advisory: advisory
  alert: alert
  binder: binder
  campaign_landing: campaign_landing
  contact_information: contact_information
  curated_list: curated_list
  decision: decision
  decision_tree: decision_tree
  decision_tree_branch: decision_tree_branch
  decision_tree_conclusion: decision_tree_conclusion
  error_page: error_page
  event: event
  executive_order: executive_order
  external_data_resource: external_data_resource
  fee: fee
  form_page: form_page
  guide_page: guide_page
  how_to_page: how_to_page
  info_details: info_details
  interstitial: interstitial
  location: location
  location_details: location_details
  news: news
  org_page: org_page
  page: page
  person: person
  regulation: regulation
  rules: rules
  service_details: service_details
  service_page: service_page
  sitewide_alert: sitewide_alert
  stacked_layout: stacked_layout
  topic_page: topic_page
  utility_drawer: utility_drawer
enabled_taxonomies:
  action_type: '0'
  adjustment_type: '0'
  advisory_publish_state: '0'
  advisory_type: '0'
  announcement_type: '0'
  billing_organizations: '0'
  binder_type: '0'
  collections: '0'
  content_type: '0'
  data_topic: '0'
  decision_participant_type: '0'
  decision_type: '0'
  document_category: '0'
  document_contacts: '0'
  document_creators: '0'
  document_other_type: '0'
  document_subjects: '0'
  document_tags: '0'
  event_type: '0'
  icons: '0'
  label: '0'
  language: '0'
  license: '0'
  location_activities: '0'
  location_icon: '0'
  location_icon_park: '0'
  rules_of_court_standing_order: '0'
  rules_of_court_type: '0'
  tags: '0'
  tx_data_resource_type: '0'
  tx_details_data_type: '0'
  tx_list_data_type: '0'
  type: '0'
  user_organization: '0'
