token: b3a1ab0c28be4e3d8e9d06f65c333205
_core:
  default_config_hash: t5W6QbLZA8s7VAoHDDldhRB2Emm1blOGOOKHMV855Gk
domain_plugin_id: siteimprovedomain_simple
prepublish_enabled: false
api_username: ''
api_key: ''
enabled_content_types:
  action: '0'
  advisory: '0'
  alert: '0'
  binder: '0'
  campaign_landing: '0'
  contact_information: '0'
  curated_list: '0'
  decision: '0'
  decision_tree: '0'
  decision_tree_branch: '0'
  decision_tree_conclusion: '0'
  error_page: '0'
  event: '0'
  executive_order: '0'
  external_data_resource: '0'
  fee: '0'
  form_page: '0'
  guide_page: '0'
  how_to_page: '0'
  info_details: '0'
  interstitial: '0'
  location: '0'
  location_details: '0'
  news: '0'
  org_page: '0'
  page: '0'
  person: '0'
  regulation: '0'
  rules: '0'
  service_details: '0'
  service_page: '0'
  stacked_layout: '0'
  topic_page: '0'
  utility_drawer: '0'
enabled_taxonomies:
  action_type: '0'
  adjustment_type: '0'
  advisory_publish_state: '0'
  advisory_type: '0'
  announcement_type: '0'
  billing_organizations: '0'
  binder_type: '0'
  collections: '0'
  content_type: '0'
  data_topic: '0'
  decision_participant_type: '0'
  decision_type: '0'
  document_category: '0'
  document_contacts: '0'
  document_creators: '0'
  document_other_type: '0'
  document_subjects: '0'
  document_tags: '0'
  event_type: '0'
  icons: '0'
  label: '0'
  language: '0'
  license: '0'
  location_activities: '0'
  location_icon: '0'
  location_icon_park: '0'
  rules_of_court_standing_order: '0'
  rules_of_court_type: '0'
  tags: '0'
  tx_data_resource_type: '0'
  tx_details_data_type: '0'
  tx_list_data_type: '0'
  type: '0'
  user_organization: '0'
