field.widget.third_party.internal_link_content_type_blacklist:
  type: sequence
  label: 'Internal Link Content Type Blacklist (for use with Entity Autocomplete)'
  sequence:
    blacklisted_content_type:
      type: string
      label: 'Blacklisted Content Type for Internal Links'
