name: mass
type: php
docroot: docroot
php_version: "7.4"
webserver_type: nginx-fpm
dbimage: massgov/mysql-sanitized:super
omit_containers:
  - db
disable_settings_management: true
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
project_tld: local
use_dns_when_possible: true
composer_version: ""
web_environment:
  - DOCKER_ENV=devel
  - MYSQL_USER=circle
  - MYSQL_PASSWORD=circle
  - MYSQL_DATABASE=circle
  - MYSQL_HOST=dbmass
  - MEMCACHED_HOST=memcached
  - DRUSH_OPTIONS_URI=https://mass.local:$DDEV_ROUTER_HTTPS_PORT
  - DTT_BASE_URL=http://mass-web
  - DTT_API_URL=http://chromedriver:9515
#  - BROWSERTEST_OUTPUT_DIRECTORY=/tmp
#  - BROWSERTEST_OUTPUT_BASE_URL=https://mass.local:$DDEV_ROUTER_HTTPS_PORT
  # - SENDMAIL_PATH=mhsendmail --smtp-addr="mailhog:1025"
  # Needed here per https://blackfire.io/docs/integrations/docker#using-the-client-for-cli-profiling
  #- BLACKFIRE_CLIENT_ID
  #- BLACKFIRE_CLIENT_TOKEN
  # Acquia Cloud - v2
  - AC_API2_KEY
  - AC_API2_SECRET
  # New Relic. Needed for deployments.
  - MASS_NEWRELIC_APPLICATION
  - MASS_NEWRELIC_KEY
  # Acquia basic auth.  Needed for tests on Acquia environments.
  - LOWER_ENVIR_AUTH_USER
  - LOWER_ENVIR_AUTH_PASS
  # For Cloudflare Terraform.
  - CLOUDFLARE_EMAIL
  - CLOUDFLARE_TOKEN

# This config.yaml was created with ddev version v1.17.7
# webimage: drud/ddev-webserver:v1.17.7
# dbimage: drud/ddev-dbserver-mariadb-10.3:v1.17.7
# dbaimage: phpmyadmin:5
# However we do not recommend explicitly wiring these images into the
# config.yaml as they may break future versions of ddev.
# You can update this config.yaml using 'ddev config'.
